language: rust
rust:
    - 1.38.0

before_install:
    # Install ZMQ
    - sudo apt-get update 
    - sudo apt-get install -y libzmq3-dev unzip protobuf-compiler nodejs npm
    - sudo apt-get clean
    # Install protoc for protoc-rust crate (automate protobuf generation)
    - curl -OLsS https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
    - unzip protoc-3.6.1-linux-x86_64.zip -d protoc3
    - rm protoc-3.6.1-linux-x86_64.zip
    # Set system protoc to protoc3 (defaults to protoc2)
    - sudo mv protoc3/bin/* /usr/local/bin/
    - sudo mv protoc3/include/* /usr/local/include/
    - rm -rf protoc3/
    # Install latest stable/nightly of rust toolchain & linter (rustfmt)
    - rustup component add rustfmt

before_script:
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    - echo $TRAVIS_REPO_SLUG

script:
    # Lint, build common
    - cargo fmt -- --check
    - cargo build