language: rust
rust:
  - stable
services:
  - docker

# Install latest nightly of rust toolchain & linter (rustfmt)
before_install:
  - rustup component add rustfmt

# Install tarpaulin image for processor
install:
  - docker pull target/consensource-sds:tarpaulin

before_script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_JOB_ID

script:
  # Lint, build common
  - cargo fmt -- --check || travis_terminate 1;
  # Output logs and run tarpaulin
  - docker run --security-opt seccomp=unconfined -e COVERALLS_TOKEN="$COVERALLS_TOKEN" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" -v "${PWD}:/tarpaulin" target/consensource-sds:tarpaulin /bin/sh -c "cd /tarpaulin; sh /run-tarpaulin.sh"
  - docker ps -a
  